# This workflow checks if the number of files imported from Snowflake is equal to the number of files in 'reference-schema' and stores the output in "schemacheck.txt"
name: files_count_check

# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["snowflake-devops-demo"]
    types:
      - completed
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  count_check:
    name: count_check
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: running_the_python_file
        env:
          GT_username: ${{ secrets.GT_USERNAME }}
          GT_password: ${{ secrets.GT_PASSWORD }}
          GT_auth_token: ${{ secrets.GT_AUTH_TOKEN }}
        

        run: |
          git config --global user.email "sunit_tanwar@merilytics.com"
          git config --global user.name "Admin"
          pip install pandas
          pip3 install PyGithub
          pip install auth
          pip install ffcount
          python migrations/number_of_files_check.py
 
         
          
          
          
