name: snowflake-devops-demo

# Controls when the action will run. 



on:
  push:
    branches:
      - master
    paths:
      - 'migrations/**.sql'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  schemachangecheck:
    name: Schema Change Check
    runs-on: ubuntu-latest
    
    
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: running_the_python_file
        env:
          GT_username: ${{ secrets.GT_USERNAME }}
          GT_password: ${{ secrets.GT_PASSWORD }}
          GT_auth_token: ${{ secrets.GT_AUTH_TOKEN }}
        

      - run: pip install pandas
      - run: pip3 install PyGithub
      - run: pip install auth
      - run: pip install ffcount
      - run: pip install snowflake-connector-python
      - run: pip install python-dotenv
      - run: git config --global user.email "sunit_tanwar@merilytics.com"
      - run: git config --global user.name "Testaccountforcon"
      - run: git rm -rf latest\ schema\ pull
      - run: git rm -rf migrations/diff.txt
      - run: git rm -rf migrations/schemacheck.txt
      - run: git commit -m "commit message"
      - run: git push origin master
      - run: |    
          python migrations/schema_comparison.py
          git ls-files
        
      - run: python migrations/number_of_files_check.py
          


         
        
        
      
