name: snowflake-devops-demo

# Controls when the action will run. Workflow will run when a .sql file is pushed to master branch in migrations directory

on:
  push:
    branches:
      - master
    paths:
      - 'migrations/**.sql'

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
# This job checks that for each table/view/procedure in Snowflake, there is a corresponding file in 'reference-pull' directory with the same definition
  schemachangecheck:
    name: Schema Change Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: running_the_python_file
        env:
# Creating an environment to access the GitHub Action Secrets in python code to connect to GitHub and Snowflake
# The GitHub and Snowflake credentials are masked using Action Secrets
          GT_username: ${{ secrets.GT_USERNAME }}
          GT_password: ${{ secrets.GT_PASSWORD }}
          GT_auth_token: ${{ secrets.GT_AUTH_TOKEN }}
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}

# Installing the libraries and then running the python code to compare GitHub and Snowflake schemas
        run: |
          pip install pandas
          pip3 install PyGithub
          pip install auth
          pip install ffcount
          python -c 'import os;print(os.environ)'
          pip install snowflake-connector-python
          pip install python-dotenv
          git config --global user.email "sunit_tanwar@merilytics.com"
          git config --global user.name "Testaccountforcon"
          git rm -rf latest-schema-pull
          git rm -rf migrations/schemacheck.txt
          git commit -m "schemacheck.txt updated"
          git push origin master
          python migrations/schema_comparison.py
          git pull
          
