name: snowflake-devops-demo

# Controls when the action will run. 



on:
  push:
    branches:
      - master
    paths:
      - 'migrations/**.sql'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  
  schemachangecheck:
    name: Schema Change Check
    runs-on: ubuntu-latest
    
    
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: running_the_python_file
        env:
          GT_username: ${{ secrets.GT_USERNAME }}
          GT_password: ${{ secrets.GT_PASSWORD }}
          GT_auth_token: ${{ secrets.GT_AUTH_TOKEN }}
        

        run: |
          pip install pandas
          pip3 install PyGithub
          pip install auth
          pip install snowflake-connector-python
          pip install python-dotenv
          python migrations/testpy2.py
          git ls-files
          


         
        
        
      
